# Change these first
owner: CaturraSocial # Your GitHub organisation or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Site
    url: https://caturra.app
    expectedStatusCodes:
      - 200
  # - name: Canary
  #   url: https://canary.caturra.app
  #   expectedStatusCodes:
  #     - 200
  - name: API Live
    url: https://caturra.app/api/v1/ping
    expectedStatusCodes:
      - 200
    delay: 5000
  # - name: API Canary
  #   url: https://canary.caturra.app/api/v1/ping
  #   expectedStatusCodes:
  #     - 200
  #   delay: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.caturra.app
  metaTags:
    - name: "robots"
      content: "noindex"
  # baseUrl: /your-repo-name
  logoUrl: https://caturra.app/logo.png
  name: Caturra Uptime
  favicon: https://caturra.app/favicon.ico
  themeUrl: https://status.caturra.app/caturra.css
  #introTitle: ""
  #introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://caturra.app?rel=status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
