# Change these first
owner: CaturraSocial # Your GitHub organisation or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Site
    url: https://caturra.social
    expectedStatusCodes:
      - 200
  - name: Alpha
    url: https://alpha.caturra.social
    expectedStatusCodes:
      - 200
  - name: PTB
    url: https://ptb.caturra.social
    expectedStatusCodes:
      - 200
    delay: 5000
  - name: API Live
    url: https://caturra.social/api/v1/ping
    expectedStatusCodes:
      - 200
      - 404
  - name: API Alpha
    url: https://alpha.caturra.social/api/v1/ping
    expectedStatusCodes:
      - 200
    delay: 5000
  - name: API PTB
    url: https://ptb.caturra.social/api/v1/ping
    expectedStatusCodes:
      - 200
    delay: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.caturra.social
  metaTags:
    - name: "robots"
      content: "noindex"
  # baseUrl: /your-repo-name
  logoUrl: https://caturra.social/logo.png
  name: Caturra Uptime
  favicon: https://caturra.social/favicon.ico
  themeUrl: https://status.caturra.social/caturra.css
  #introTitle: ""
  #introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://caturra.social?rel=status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
